### ISSUE TITLE
create-program fails when validating a shader with samplers of different types

### ISSUE THREAD

**Issue by snoury** [ztellman/penumbra#32]
The _create-program_ method calls _gl-validate-program_ after shader compilation but fails when a shader is defined with samplers of different types because no texture units have been assigned to them before validation (in src/penumbra/opengl/shader.clj, line 183).

According to the OpenGL documentation for _glValidateProgram_, this is considered as an error:

> This function mimics the validation operation that OpenGL implementations must perform when rendering commands are issued while programmable shaders are part of current state.
> The error GL_INVALID_OPERATION will be generated by glBegin, glRasterPos, or any command that performs an implicit call to glBegin if:
>   any two active samplers in the current program object are of different types, but refer to the same texture image unit,
>   any active sampler in the current program object refers to a texture image unit where fixed-function fragment processing accesses a texture target that does not match the sampler type [...]

The behavior of _glValidateProgram_ seems to be varying between OS and driver vendors.
It doesn't report any errors using Nvidia's driver for Linux but fails with Apple's Mac OS X driver:

> *** Error validating program:
> Validation Failed: Sampler error:
>  Samplers of different types use the same texture image unit.
>   - or -
>  A sampler's texture unit is out of range (greater than max allowed or negative).

An optional list of textures could be passed when calling _create-program_ in order to bind them just before the validation, in the same fashion as the _uniform_ method.

**Comment by giantchen2012** [comment]
you video/graphic card is not support the feature you used in OpenGL,you can switch to a graphic card that supports the feature you use in system settings,or change a graphic card to support it,hope to be helpful.
